version: '3.1'

services:
  mongo:
    image: mongo:5
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tests
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
